### ISSUE TITLE
Bug. No error message and no uploading of .txt file

### ISSUE THREAD

**Issue by AAKrasnova** [pechorka/adhd-reader#10]
Windows.
I sent two txt files. But only one was uploaded. Second not without error message
![image](https://user-images.githubusercontent.com/10058916/225628773-86f45670-a3fa-44d9-8efe-4ba049dc32ed.png)

![image](https://user-images.githubusercontent.com/10058916/225628875-d6f4c692-43ba-44d1-8b9b-79f58126eb8e.png)

Problematic file itself
[Google’s medical AI was super accurate in a lab. Real life was a different story..txt](https://github.com/pechorka/adhd-reader/files/10991197/Google.s.medical.AI.was.super.accurate.in.a.lab.Real.life.was.a.different.story.txt)

PS. if I send only this file there is no error response too: 
![image](https://user-images.githubusercontent.com/10058916/225629165-b3b69414-d52a-4751-8afe-bd8d7cc1c5d7.png)

**Comment by pechorka** [comment]
It was related to this bug https://github.com/pechorka/adhd-reader/issues/9
Works now since I fixed Issue 9
