### ISSUE TITLE
Stability. Checking for file format. Return error if it's not .txt.

### ISSUE THREAD

**Issue by AAKrasnova** [pechorka/adhd-reader#18]
Currently, the bot can handle only .txt files and telegram messages as its input. 

When trying to give .pdf as an input bot says "Text is not in UTF-8 encoding"
![image](https://user-images.githubusercontent.com/10058916/225874959-0dcee638-9fc4-41d8-abe6-7339437b1d50.png)

It's not the correct reason to put user input down, so we need to add more clarity.
We need to check the file format and the new error message:
`Unsupported file format. Please input .txt file or send a message. We currently do not support other file formats.`

**Comment by pechorka** [comment]
Added file type check
