### ISSUE TITLE
List command. Misbehavior after deleting entry

### ISSUE THREAD

**Issue by AAKrasnova** [pechorka/adhd-reader#2]
1. Command "list"
2. Delete one entry (флаконе)
3. Click on next after deleted (гипотетическое)
4. Selected next after clicked entry (какие установки)

![image](https://user-images.githubusercontent.com/10058916/224560494-e71eec9a-576b-4822-a540-78e0a3f80e1d.png)

**Comment by pechorka** [comment]
Fixed
