### ISSUE TITLE
Post with huge first paragraph not working

### ISSUE THREAD

**Issue by AAKrasnova** [pechorka/adhd-reader#25]
Sent post: https://t.me/realTorshin/186

Got error: `Faled to save text: text name В 2008 году под моим управлением находился очень сложный и интересный проект: нужно было подключить более 10 000 отделений Почты России в единую сеть. Каждое подключение состояло из нескольких этапов, которые выполняли разные люди, а происходило это все одновременно в нескольких сотнях населенных пунктов по всей стране. В проекте были задействованы десятки тысяч людей! is too long, max length is 255 (less if you use emojis/non-ascii symbols)`

If there is no clear first-line name, then just take first 250 symbols (or less)

**Comment by pechorka** [comment]
Fixed
