### ISSUE TITLE
Bug. Not working basic scenario

### ISSUE THREAD

**Issue by AAKrasnova** [pechorka/adhd-reader#3]
added files
![image](https://user-images.githubusercontent.com/10058916/224749268-95a6d65f-6220-4d27-b095-3b786ef2fd96.png)
clicked Read
![image](https://user-images.githubusercontent.com/10058916/224749350-8e1c8a2f-77df-4e5b-87d7-14fb8591ac8e.png)

no buttons "Next" appeared

same with list and older texts
![image](https://user-images.githubusercontent.com/10058916/224749503-d1f011dc-8d5f-4c20-8b36-883ab4377d66.png)
except one.... which is not very different from others
![image](https://user-images.githubusercontent.com/10058916/224749605-a7a81c03-46aa-45e8-9d72-cb8921e0e14e.png)

**Comment by pechorka** [comment]
Fixed
