### ISSUE TITLE
Feature. Get "The end" message with the last chunk

### ISSUE THREAD

**Issue by AAKrasnova** [pechorka/adhd-reader#6]
![image](https://user-images.githubusercontent.com/10058916/225335406-8370e793-57e9-44eb-9dd4-47a2452cc523.png)

now you need to press "Next" to get "Text .... is finished". 
I think it will be better when I get the last chunk and this message without pressing "Next". Save time AND a bit of nerve. Because I felt anxious when I read logically the last sentence of an article or a book... but there is a button "Next"!

**Comment by pechorka** [comment]
Done. Also there no more prev button on first chunk
